spring.application.name=hltgq-site

# ===== KingbaseES v8 æ°æ®æº =====
spring.datasource.primary.jdbc-url=jdbc:postgresql://10.68.18.5:54321/qixiao-apaas?currentSchema=qixiao-apaas
spring.datasource.primary.username=SYSTEM
spring.datasource.primary.password=T!3>kGit70DZ
spring.datasource.primary.driver-class-name=org.postgresql.Driver

# ===== MyBatis-Plus =====
mybatis-plus.type-handlers-package=com.qgyun.hltgq.hltgqsite.handler
mybatis-plus.configuration.map-underscore-to-camel-case=false
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
# ===== æ¥å¿ =====
logging.file.path=/app/logs

# Jackson
spring.jackson.serialization.write-bigdecimal-as-plain=true
